"use client";

const STORAGE_KEYS = {
  USERNAME: "username",
  PASSWORD: "password",
  IS_AUTOGENERATED: "is_autogenerated",
} as const;

const isBrowser = typeof window !== "undefined";

class StorageService {
  private static instance: StorageService;
  private username: string | null = null;
  private password: string | null = null;
  private isAutogenerated: boolean | null = null;

  private constructor() {
    if (isBrowser) {
      // Initialize values from localStorage
      this.username = localStorage.getItem(STORAGE_KEYS.USERNAME);
      this.password = localStorage.getItem(STORAGE_KEYS.PASSWORD);
      this.isAutogenerated =
        localStorage.getItem(STORAGE_KEYS.IS_AUTOGENERATED) === "true";
    }
  }

  public static getInstance(): StorageService {
    if (!StorageService.instance) {
      StorageService.instance = new StorageService();
    }
    return StorageService.instance;
  }

  private generateRandomPassword(): string {
    return Math.random().toString(36).slice(-8);
  }

  public getUsername(): string {
    if (!this.username) {
      // Generate a random username if none exists
      this.username = `user_${Math.random().toString(36).slice(-6)}`;
      if (isBrowser) {
        localStorage.setItem(STORAGE_KEYS.USERNAME, this.username);
        this.setIsAutogenerated(true);
      }
    }
    return this.username;
  }

  public getPassword(): string {
    if (!this.password) {
      // Generate a random password if none exists
      this.password = this.generateRandomPassword();
      if (isBrowser) {
        localStorage.setItem(STORAGE_KEYS.PASSWORD, this.password);
      }
    }
    return this.password;
  }

  public setCredentials(username: string, password: string): void {
    this.username = username;
    this.password = password;
    if (isBrowser) {
      localStorage.setItem(STORAGE_KEYS.USERNAME, username);
      localStorage.setItem(STORAGE_KEYS.PASSWORD, password);
      this.setIsAutogenerated(false);
    }
  }

  public clearCredentials(): void {
    this.username = null;
    this.password = null;
    this.isAutogenerated = null;
    if (isBrowser) {
      localStorage.removeItem(STORAGE_KEYS.USERNAME);
      localStorage.removeItem(STORAGE_KEYS.PASSWORD);
      localStorage.removeItem(STORAGE_KEYS.IS_AUTOGENERATED);
    }
  }

  public hasCredentials(): boolean {
    return !!this.username && !!this.password;
  }

  public hasUsernameAutogenerated(): boolean {
    return !!localStorage.getItem(STORAGE_KEYS.IS_AUTOGENERATED);
  }

  public isUsernameAutogenerated(): boolean {
    if (this.isAutogenerated === null) {
      this.isAutogenerated =
        isBrowser &&
        localStorage.getItem(STORAGE_KEYS.IS_AUTOGENERATED) === "true";
    }
    return this.isAutogenerated || false;
  }

  private setIsAutogenerated(value: boolean): void {
    this.isAutogenerated = value;
    if (isBrowser) {
      localStorage.setItem(STORAGE_KEYS.IS_AUTOGENERATED, value.toString());
    }
  }
}

export const storage = StorageService.getInstance();
